# Generated by Django 5.0 on 2023-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airplane",
            name="passenger_assumptions",
        ),
        migrations.AddField(
            model_name="airplane",
            name="passengers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
